### ISSUE TITLE
Please mention your teacher name

### ISSUE THREAD

**Issue by suhasdeshpande** [pathakashish/HobbyAssemblyLanguageProejcts#3]
I forgot all about third year engineering and I don’t remember writing or going through this exercises! Mind mentioning the name of the class in your comments? :)

**Comment by pathakashish** [comment]
I wrote these programs just as hobby.

Though from what I vaguely remember, there was assignments for interfacing mouse and printer driver in hardware lab.
Again, I don't remember specific details but assignment was probably done in C for course work. And then, this code was written just for hobby. Take the C part with pinch of salt though because my memory has track record of not serving me well.
